version: '2'
services:

  # The Application
  web:
    image: hitalos/laravel:latest
    ports:
        - 80:80
    volumes:
        - ./:/var/www
    links:
        - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=hsg_portal"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    ports:
        - "33061:3306"

volumes:
  dbdata:
